title: "OX1Digital"
author: "Neil Lawrence"
url: "https://www.ox1digital.co.uk"
description: "My personal site and blog"

# Default Open Graph image
image: "/img/site_image.jpg"

collections:
 projects:
    output: true  # Whether to output files in this collection
    permalink: /projects/:year/:month/:day/:title  # Permalink structure for project pages

markdown: kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
 - jekyll-feed
 - jekyll-redirect-from

feed:
  path: feed.xml
  title: "OX1Digital"
  description: "My personal blog and information about me"

